// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmfaLPIkq9pPt86Dr20UevG6Hff9nBClE',
    appId: '1:1022510105024:web:e9957d700dbc160945c825',
    messagingSenderId: '1022510105024',
    projectId: 'budget-app-flutter-1678f',
    authDomain: 'budget-app-flutter-1678f.firebaseapp.com',
    storageBucket: 'budget-app-flutter-1678f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Efr2Pxz-qrUaKY1YKFvksp3dqqCwdk0',
    appId: '1:1022510105024:android:a8b46d2b6938d11345c825',
    messagingSenderId: '1022510105024',
    projectId: 'budget-app-flutter-1678f',
    storageBucket: 'budget-app-flutter-1678f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoKop1q6w5vg2i7N3DumfxttwXGXDulmI',
    appId: '1:1022510105024:ios:1517c6acddb9a6dc45c825',
    messagingSenderId: '1022510105024',
    projectId: 'budget-app-flutter-1678f',
    storageBucket: 'budget-app-flutter-1678f.firebasestorage.app',
    iosBundleId: 'com.antigravity.budget.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoKop1q6w5vg2i7N3DumfxttwXGXDulmI',
    appId: '1:1022510105024:ios:1517c6acddb9a6dc45c825',
    messagingSenderId: '1022510105024',
    projectId: 'budget-app-flutter-1678f',
    storageBucket: 'budget-app-flutter-1678f.firebasestorage.app',
    iosBundleId: 'com.antigravity.budget.budgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmfaLPIkq9pPt86Dr20UevG6Hff9nBClE',
    appId: '1:1022510105024:web:13f0c03d7118ae3f45c825',
    messagingSenderId: '1022510105024',
    projectId: 'budget-app-flutter-1678f',
    authDomain: 'budget-app-flutter-1678f.firebaseapp.com',
    storageBucket: 'budget-app-flutter-1678f.firebasestorage.app',
  );
}
